version: '3'

services:
    oasipdb:
        image: mysql
        container_name: oasipdb
        ports:
            - 3306:3306
        volumes:
            - ./database:/docker-entrypoint-initdb.d
            - ./database/datadir:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: oasipat1
            LANG: en_US.UTF-8
            
    backend:
        image: backendimg
        container_name: backend
        build:
            context: ./oasip-server
        depends_on:
            - oasipdb
        links:
            - oasipdb:mysql
        ports:
            - 5000:8080
        restart: always

    frontend:
        image: frontendimg
        container_name: frontend
        build:
            context: ./oasip-frontend
        depends_on:
            - oasipdb
            - backend
        ports:
            - 80:80

    reverse-proxy:
        image: nginx
        container_name: reverseproxy
        depends_on:
            - backend
            - frontend
        volumes:
            - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8080:80
